# These are supported funding model platforms

github: ['official-antique']
ko_fi: 'antiquecodes'
custom: ['buymeacoffee.com/antiquecodes', 'paypal.com/paypalme/officialantique', 'reddit.com/u/antique_codes', 'twitch.tv/official_antique', 'twitter.com/antique_codes']
